<?php

namespace ContainerNSBXY1J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_82D_IAgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.82D.IAg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.82D.IAg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'ticket' => ['privates', '.errored..service_locator.82D.IAg.App\\Entity\\Ticket', NULL, 'Cannot autowire service ".service_locator.82D.IAg": it needs an instance of "App\\Entity\\Ticket" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'ticket' => 'App\\Entity\\Ticket',
        ]);
    }
}
