<?php

namespace ContainerD6wFuTR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4l0YB7WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4l0YB7W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4l0YB7W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'prd' => ['privates', '.errored..service_locator.4l0YB7W.App\\Entity\\Prd', NULL, 'Cannot autowire service ".service_locator.4l0YB7W": it needs an instance of "App\\Entity\\Prd" but this type has been excluded in "config/services.yaml".'],
        ], [
            'prd' => 'App\\Entity\\Prd',
        ]);
    }
}
