<?php

namespace ContainerD6wFuTR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LGGL066Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lGGL066' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lGGL066'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ticket' => ['privates', '.errored..service_locator.lGGL066.App\\Entity\\Ticket', NULL, 'Cannot autowire service ".service_locator.lGGL066": it needs an instance of "App\\Entity\\Ticket" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ticket' => 'App\\Entity\\Ticket',
        ]);
    }
}
