<?php

namespace ContainerWVFpkiZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P68VRpTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p68VRpT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p68VRpT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PrdController::delete' => ['privates', '.service_locator.uf73EwL', 'get_ServiceLocator_Uf73EwLService', true],
            'App\\Controller\\PrdController::edit' => ['privates', '.service_locator.uf73EwL', 'get_ServiceLocator_Uf73EwLService', true],
            'App\\Controller\\PrdController::index' => ['privates', '.service_locator.BeiCmOK', 'get_ServiceLocator_BeiCmOKService', true],
            'App\\Controller\\PrdController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PrdController::show' => ['privates', '.service_locator.4l0YB7W', 'get_ServiceLocator_4l0YB7WService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TicketController::chooseTicket' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TicketController::delete' => ['privates', '.service_locator.82D.IAg', 'get_ServiceLocator_82D_IAgService', true],
            'App\\Controller\\TicketController::edit' => ['privates', '.service_locator.82D.IAg', 'get_ServiceLocator_82D_IAgService', true],
            'App\\Controller\\TicketController::index' => ['privates', '.service_locator.2JKuakw', 'get_ServiceLocator_2JKuakwService', true],
            'App\\Controller\\TicketController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TicketController::show' => ['privates', '.service_locator.lGGL066', 'get_ServiceLocator_LGGL066Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PrdController:delete' => ['privates', '.service_locator.uf73EwL', 'get_ServiceLocator_Uf73EwLService', true],
            'App\\Controller\\PrdController:edit' => ['privates', '.service_locator.uf73EwL', 'get_ServiceLocator_Uf73EwLService', true],
            'App\\Controller\\PrdController:index' => ['privates', '.service_locator.BeiCmOK', 'get_ServiceLocator_BeiCmOKService', true],
            'App\\Controller\\PrdController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PrdController:show' => ['privates', '.service_locator.4l0YB7W', 'get_ServiceLocator_4l0YB7WService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TicketController:chooseTicket' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TicketController:delete' => ['privates', '.service_locator.82D.IAg', 'get_ServiceLocator_82D_IAgService', true],
            'App\\Controller\\TicketController:edit' => ['privates', '.service_locator.82D.IAg', 'get_ServiceLocator_82D_IAgService', true],
            'App\\Controller\\TicketController:index' => ['privates', '.service_locator.2JKuakw', 'get_ServiceLocator_2JKuakwService', true],
            'App\\Controller\\TicketController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TicketController:show' => ['privates', '.service_locator.lGGL066', 'get_ServiceLocator_LGGL066Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PrdController::delete' => '?',
            'App\\Controller\\PrdController::edit' => '?',
            'App\\Controller\\PrdController::index' => '?',
            'App\\Controller\\PrdController::new' => '?',
            'App\\Controller\\PrdController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TicketController::chooseTicket' => '?',
            'App\\Controller\\TicketController::delete' => '?',
            'App\\Controller\\TicketController::edit' => '?',
            'App\\Controller\\TicketController::index' => '?',
            'App\\Controller\\TicketController::new' => '?',
            'App\\Controller\\TicketController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PrdController:delete' => '?',
            'App\\Controller\\PrdController:edit' => '?',
            'App\\Controller\\PrdController:index' => '?',
            'App\\Controller\\PrdController:new' => '?',
            'App\\Controller\\PrdController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TicketController:chooseTicket' => '?',
            'App\\Controller\\TicketController:delete' => '?',
            'App\\Controller\\TicketController:edit' => '?',
            'App\\Controller\\TicketController:index' => '?',
            'App\\Controller\\TicketController:new' => '?',
            'App\\Controller\\TicketController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
