<?php

namespace ContainerBwx9LiW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicketService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.82D.IAg.App\Entity\Ticket' shared service.
     *
     * @return \App\Entity\Ticket
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.82D.IAg": it needs an instance of "App\\Entity\\Ticket" but this type has been excluded in "config/services.yaml".');
    }
}
