<?php

namespace ContainerX5IPiH1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4l0YB7W.App\Entity\Prd' shared service.
     *
     * @return \App\Entity\Prd
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4l0YB7W": it needs an instance of "App\\Entity\\Prd" but this type has been excluded in "config/services.yaml".');
    }
}
