<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXYrBqcL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXYrBqcL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXYrBqcL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXYrBqcL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXYrBqcL\App_KernelDevDebugContainer([
    'container.build_hash' => 'XYrBqcL',
    'container.build_id' => '52a4b7ee',
    'container.build_time' => 1715121297,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXYrBqcL');
