<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBwx9LiW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBwx9LiW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBwx9LiW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBwx9LiW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBwx9LiW\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bwx9LiW',
    'container.build_id' => '99b2f6a1',
    'container.build_time' => 1715244585,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBwx9LiW');
