<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD6wFuTR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD6wFuTR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD6wFuTR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD6wFuTR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD6wFuTR\App_KernelDevDebugContainer([
    'container.build_hash' => 'D6wFuTR',
    'container.build_id' => 'd46092c7',
    'container.build_time' => 1715244224,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD6wFuTR');
